/**
 * Container that displays a generated dashboard with a toggle between
 * the live rendered view, the raw JSON spec, and a Cytoscape diagram of
 * how the spec's primitives are wired together.
 */

import { useState } from "react";
import Box from "@mui/material/Box";
import Chip from "@mui/material/Chip";
import Stack from "@mui/material/Stack";
import ToggleButton from "@mui/material/ToggleButton";
import ToggleButtonGroup from "@mui/material/ToggleButtonGroup";
import Typography from "@mui/material/Typography";
import DashboardIcon from "@mui/icons-material/Dashboard";
import DataObjectIcon from "@mui/icons-material/DataObject";
import AccountTreeIcon from "@mui/icons-material/AccountTree";

import type { Dashboard } from "../spec";
import { Renderer } from "../renderer/Renderer";
import { DashboardJsonView } from "./DashboardJsonView";
import { DashboardDiagramView } from "./DashboardDiagramView";

type Mode = "dashboard" | "json" | "diagram";

interface DashboardViewProps {
  dashboard: Dashboard;
  model: string;
}

export function DashboardView({ dashboard, model }: DashboardViewProps) {
  const [mode, setMode] = useState<Mode>("dashboard");

  return (
    <Stack spacing={2}>
      <Stack direction="row" alignItems="center" spacing={1.5}>
        <Typography variant="h6" sx={{ fontWeight: 600, flexGrow: 1 }}>
          {dashboard.title}
        </Typography>
        <Chip size="small" color="success" label={model} title={`Generated by ${model}`} />
        <ToggleButtonGroup
          size="small"
          value={mode}
          exclusive
          onChange={(_, v: Mode | null) => v && setMode(v)}
          aria-label="View mode"
        >
          <ToggleButton value="dashboard" aria-label="Dashboard">
            <DashboardIcon fontSize="small" sx={{ mr: 0.5 }} />
            Dashboard
          </ToggleButton>
          <ToggleButton value="json" aria-label="JSON">
            <DataObjectIcon fontSize="small" sx={{ mr: 0.5 }} />
            JSON
          </ToggleButton>
          <ToggleButton value="diagram" aria-label="Diagram">
            <AccountTreeIcon fontSize="small" sx={{ mr: 0.5 }} />
            Diagram
          </ToggleButton>
        </ToggleButtonGroup>
      </Stack>

      <Box>
        {mode === "dashboard" ? (
          <Renderer dashboard={dashboard} />
        ) : mode === "json" ? (
          <DashboardJsonView dashboard={dashboard} />
        ) : (
          <DashboardDiagramView dashboard={dashboard} />
        )}
      </Box>
    </Stack>
  );
}
